### ISSUE TITLE
 Extract PDF utility not working

### ISSUE THREAD

**Issue by meetzaveri** [infogram/infogram-node#10]
I did as mentioned passing `project id` and still there is no data logging(showing empty object) into `console.log`. So if data is empty object, what would filesystem API of node would write ? 

Screenshot - http://prntscr.com/jyy88t 

@torbjon Do you know alternative way to how to extract as a pdf ?

Also when I am using this API of `getProject` method without extra arguments then data is been logging correctly. So that states that when extra arguments are supplied such as `{format : pdf}` then it's showing empty object while data is been logging.

Waiting for response. Thanks

**Comment by torbjon** [comment]
@meetzaveri please check latest update, should work
